limbo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index),
    path("admin/", admin.site.urls),
    path("train/", include("train.urls")),
    path("predict/", include("predict.urls")),
]

predict/urls.py
from django.urls import path
from . import views

app_name = "predict"
urlpatterns = [
    path('', views.index, name="index")
]

train/urls.py
from django.urls import path
from . import views

app_name = "train"
urlpatterns = [
     path('', views.index, name="index")
]

predict/models.py
from django.db import models

# Create your models here.

train/models.py
from django.db import models

# Create your models here.

limbo/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'front.html')

predict/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Hello this is the prediction main page.")

train/views.py
from django.shortcuts import render
from django.http import HttpResponse

class State:
    def __init__(self, cmd: int, task: str, algorithm: str):
        self.last_cmd = cmd
        self.task = task
        self.algorithm = algorithm

# Create your views here.
def index(request):

    if request.method == 'POST':
        cmd = request.POST['cmd']
        if cmd == 'task_chosen':
            task: str = request.POST['task']
            state = State(cmd, task, None)

        elif cmd == 'algorithm_chosen':
            task: str = request.POST['task_chosen']
            algorithm: str = request.POST['algorithm']
            state = State(cmd, task, algorithm)

        else:
            state = State(0, None, None)

    else:
        state = State(0, None, None)

    return render(request, 'train/main.html', {'state': state})

templates/front.html
{% extends "main.html" %}

{% block content %}

<div class="flex items-center justify-center">
    <div class="flex flex-col md:flex-row w-2/3">
        <div class="w-full md:w-1/3">
            {% load static %}
            <img src="{% static 'icon.png' %}" alt="Your cursor hovering over the icon." class="w-full h-auto">
        </div>

        <div class="w-full md:w-2/3 p-4">
            <h1 class="text-4xl font-extrabold text-slate-700">🪄Uranai<sup class="text-base text-red-600 font-mono"> ghostwriter</sup></h1>
            <br>
            <p class="text-base font-mono">allows you to classify entities into categories or predict future trends in light of a dataset(s) you provide the model with. On the basis of your task, it provides separate sets of algorithms, of which you can configure the hyperparameters to suit your situation. Depending on the quality of your data as well as the degree to which you were able to tune the parameters, the algorithms perform at exceptional rates. <a href="{% url 'train:index' %}" class="text-sky-800"><u>Let's start</u></a></p>
        </div>
    </div>
</div>

{% endblock content %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>.::Uranaidoori::.</title>
</head>
<body>
    <header class="sticky top-0 z-10">
        <section class="max-w-4xl mx-auto p-4 flex justify-between items-center">
            {% load static %}
            <img class="h-24 w-auto" src="{% static 'uranai.png' %}" alt="Uranai sama no te to rogo desu.">
            <div>
                <button id="hamburger-button" class="text-2xl md:hidden focus:outline-none">
                    &#9776;
                </button>
                <nav class="hidden font-light md:block space-x-8 text-base font-sans" aria-label="main">
                    <a href="/">🏰 Home</a>
                    <a href="#">📚 Manual</a>
                    <a href="{% url 'train:index' %}">🤖 Train model</a>
                    <a href="{% url 'predict:index' %}">🔮 Forecast</a>
                </nav>
            </div>
        </section>
    </header>

    {% block content %}
    {% endblock content %}

    {% load static %}
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

train/templates/train/main.html
{% extends "main.html" %}

{% block content %}

<div class="flex items-center justify-center">
    <div class="w-2/3 p-4" style="border: 1px solid gray;">
        
        <form method="post" action="{% url 'train:index' %}">
            {% csrf_token %}
            <label for="tasks">Choose the task:</label>

            <select name="task" id="tasks" onchange="send(this, 'task_chosen');">
                <option value="" selected disabled hidden>-------- Choose task --------</option>
                <option value="classification">Supervised Learning - Classification</option>
                <option value="regression">Supervised Learning - Regression</option>
                <option value="unsupervised">Unsupervised Learning - Clustering, PCA</option>
            </select>
            
            {% if state.task == 'classification' %}
            <br>
            <br>
            <label for="algorithms_cls">Choose the classification algorithm:</label>
            
            <select name="algorithm" id="algorithms_cls" onchange="send(this, 'algorithm_chosen');">
                <option value="" selected disabled hidden>-------- Choose algorithm --------</option>
                <option value="blr">Binary classification</option>
                <option value="svc">Support Vector Machine (Binary)</option>
                <option value="net">Artificial Neural Network</option>
            </select>
            {% elif state.task == 'regression' %}
            <br>
            <br>
            <label for="algorithms_reg">Choose the regression algorithm:</label>

            <select name="algorithm" id="algorithms_reg" onchange="send(this, 'algorithm_chosen');">
                <option value="" selected disabled hidden>-------- Choose algorithm --------</option>
                <option value="ldf">Linear discriminant function</option>
                <option value="svr">Support Vector Machine</option>
                <option value="net">Artificial Neural Network</option>
            </select>
            {% endif %}

            {% if state.algorithm == 'svc' %}
            <br>
            <br>
            <label for="svm_param_c">Regularization parameter C</label>
            <input type="number" id="svm_param_c" name="svm_param_c" value=1.0>
            <br>
            <br>
            <label for="svm_param_kernel">Kernel</label>
            <select name="svm_param_kernel" id="svm_param_kernel">
                <option value="linear">linear</option>
                <option value="poly">polynomial</option>
                <option value="rbf">radial basis function</option>
            </select>
            <br>
            <br>
            <label for="svm_param_degree">Degree (only for polynomial kernel)</label>
            <input type="number" id="svm_param_degree" name="svm_param_degree" value=3>
            <br>
            <br>
            <label for="input_dataset">Select input dataset:</label>
            <input type="file" id="input_dataset", name="input_dataset">
            <br>
            <br>
            <button type="submit">Submit</button>
            {% endif %}

            <input type="hidden" id="cmd" name="cmd">
            <input type="hidden" id="task" name="task_chosen" value="{{ state.task }}">
            <input type="hidden" id="algorithm" name="algorithm_chosen" value="{{ state.algorithm }}">
        </form>

    </div>
</div>

{% endblock content %}